# Generated by Django 4.2.7 on 2025-09-25 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_value_alter_event_venue_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='proposal_validity_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('proposta_pendente', 'Proposta Pendente'), ('proposta_enviada', 'Proposta Enviada'), ('proposta_recusada', 'Proposta Recusada'), ('proposta_aceita', 'Proposta Aceita'), ('em_execucao', 'Evento em Execução'), ('pos_evento', 'Pós Evento'), ('concluido', 'Evento Concluído')], default='proposta_pendente', max_length=30),
        ),
    ]
