# Generated by Django 4.2.7 on 2025-09-27 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0003_company_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_customer_id', models.CharField(help_text='Customer ID from payment provider', max_length=255)),
                ('provider_payment_method_id', models.CharField(help_text='Payment method ID from payment provider', max_length=255)),
                ('card_brand', models.CharField(choices=[('visa', 'Visa'), ('mastercard', 'Mastercard'), ('amex', 'American Express'), ('elo', 'Elo'), ('hipercard', 'Hipercard'), ('discover', 'Discover'), ('diners', 'Diners Club'), ('other', 'Outro')], max_length=20)),
                ('card_last_four', models.CharField(help_text='Last 4 digits of the card', max_length=4)),
                ('card_exp_month', models.IntegerField(help_text='Card expiration month')),
                ('card_exp_year', models.IntegerField(help_text='Card expiration year')),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to='users.company')),
            ],
            options={
                'verbose_name': 'Payment Method',
                'verbose_name_plural': 'Payment Methods',
                'ordering': ['-is_default', '-created_at'],
            },
        ),
    ]
